#!/usr/bin/env python3
import os
import subprocess
import shlex
import csv
import sys
from datetime import datetime

# ==============================================================================
# CONFIGURATION: RUN & PATH RESOLUTION
# ==============================================================================
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
RUNS_DIR = os.path.join(BASE_DIR, "runs")

# 1. Dynamically locate the latest run folder from upstream processing
if not os.path.exists(RUNS_DIR) or not os.listdir(RUNS_DIR):
    print("[Error] No active run folders found. Please run Stage 1 and Stage 2A first.")
    sys.exit(1)

all_runs = sorted([d for d in os.listdir(RUNS_DIR) if os.path.isdir(os.path.join(RUNS_DIR, d))])
TARGET_RUN = all_runs[-1]
RUN_PATH = os.path.join(RUNS_DIR, TARGET_RUN)

# 2. Dynamically identify the latest dereplicated data folder generated by Stage 2A
all_derep_folders = sorted([d for d in os.listdir(RUN_PATH) if d.startswith("dereplicated_data_")])
if not all_derep_folders:
    print(f"[Error] No dereplicated data found inside run folder: {TARGET_RUN}")
    print("Please execute 'dereplication_diagnostic.py' first.")
    sys.exit(1)

INPUT_BASE = os.path.join(RUN_PATH, all_derep_folders[-1])
TIMESTAMP = datetime.now().strftime("%Y%m%d_%H%M%S")
OUTPUT_BASE = os.path.join(RUN_PATH, f"denoised_data_{TIMESTAMP}")
LOG_DIR = os.path.join(RUN_PATH, "logs", f"denoising_{TIMESTAMP}")

LOCI = ["MiFish_12S", "MarVer3_16S"]

def run_denoising():
    print(f"\n>>> Stage 2B: Starting Automated UNOISE3 Denoising")
    print(f">>> Target Run Folder:      {TARGET_RUN}")
    print(f">>> Input Dereplicated Base: {INPUT_BASE}")
    os.makedirs(OUTPUT_BASE, exist_ok=True)
    os.makedirs(LOG_DIR, exist_ok=True)

    summary_data = []

    for locus in LOCI:
        locus_in = os.path.join(INPUT_BASE, locus)
        locus_out = os.path.join(OUTPUT_BASE, locus)
        if not os.path.exists(locus_in): 
            continue
        os.makedirs(locus_out, exist_ok=True)

        # Look for the .fa variants written by Stage 2A
        files = [f for f in os.listdir(locus_in) if f.endswith("_unique.fa")]

        for f in files:
            sample_id = f.replace("_unique.fa", "")
            fa_in = os.path.join(locus_in, f)
            
            zotu_out = os.path.join(locus_out, f"{sample_id}_zotus.fa")
            report_out = os.path.join(locus_out, f"{sample_id}_unoise_report.txt")
            log_file = os.path.join(LOG_DIR, f"{sample_id}_{locus}_denoise.log")
            
            # USEARCH v12 UNOISE3 Command Syntax
            # -zotus: Generates exact sequence variants (ZOTUs)
            # -tabbedout: Detailed report tracking error corrections
            # -minsize: Drops low-abundance artifacts below 8 reads
            cmd = [
                "usearch", "-unoise3", fa_in,
                "-zotus", zotu_out,
                "-tabbedout", report_out,
                "-minsize", "8"
            ]

            print(f"  Denoising {sample_id} ({locus})...")
            
            completed = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
            
            with open(log_file, "w") as lh:
                lh.write(completed.stdout)

            if completed.returncode == 0:
                print(f"    [Success] Denoised ZOTUs written to file.")
                summary_data.append([sample_id, locus, "Success", zotu_out])
            else:
                error_msg = completed.stdout.strip()[:60].replace("\n", " ")
                print(f"    [Error Failed] Check log file: {os.path.basename(log_file)}")
                summary_data.append([sample_id, locus, "Failed", f"Error: {error_msg}"])

    # ==========================================
    # FINAL AUDIT TRAIL
    # ==========================================
    audit_file = os.path.join(OUTPUT_BASE, "denoising_audit_trail.csv")
    with open(audit_file, "w", newline="") as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(["Sample", "Locus", "Status", "ZOTU_File_Path"])
        writer.writerows(summary_data)

    print(f"\n[Complete] ZOTUs generated in: {OUTPUT_BASE}")
    print(f"[Report] Denoising audit saved to: {audit_file}")

if __name__ == "__main__":
    run_denoising()
